# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gymMentor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    rn_path = '../node_modules/react-native'
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
    ]

    pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'


  # Pods for gymMentor
  pod 'google-cast-sdk', '~> 3'



  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


end



post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end